// COMMON
export const CLEAN_STATE = 'CLEAN_STATE';
export const SET_RECALCULATE_LAYOUT_SCROLL = 'SET_RECALCULATE_LAYOUT_SCROLL';
export const SUCCESS_RECALCULATE_LAYOUT_SCROLL =
  'SUCCESS_RECALCULATE_LAYOUT_SCROLL';

// API
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'show_message';
export const HIDE_MESSAGE = 'hide_message';
export const TOGGLE_APP_DRAWER = 'toggle_app_drawer';
export const UPDATING_CONTENT = 'updating_content';

//APP SETTING
export const TOGGLE_NAV_COLLAPSED = 'TOGGLE_NAV_COLLAPSED';
export const SET_INITIAL_PATH = 'SET_INITIAL_PATH';
export const SET_NAVIGATE_AFTER_INTERMEDIA = 'SET_NAVIGATE_AFTER_INTERMEDIA';

// AUTH
export const LOGIN_WITH_EMAIL_PASSWORD = 'LOGIN_WITH_EMAIL_PASSWORD';
export const REQUEST_LOGIN_OTP = 'REQUEST_LOGIN_OTP';
export const REQUEST_SIGNUP_OTP = 'REQUEST_SIGNUP_OTP';
export const CHANGE_ADRESS_OTP = 'CHANGE_ADRESS_OTP';
export const CONFIRM_LOGIN_OTP = 'CONFIRM_LOGIN_OTP';
export const CONFIRM_SIGNUP_OTP = 'CONFIRM_SIGNUP_OTP';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const REQUEST_FORGOT_PASSWORD_OTP = 'REQUEST_FORGOT_PASSWORD_OTP';
export const CONFIRM_FORGOT_PASSWORD_OTP = 'CONFIRM_FORGOT_PASSWORD_OTP';
export const LOGIN_WITH_OAUTH = 'LOGIN_WITH_OAUTH';
export const LOGOUT = 'LOGOUT';
export const SET_LOGIN_REDIRECT_TO = 'SET_LOGIN_REDIRECT_TO';
export const INCREASE_LOGIN_ATTEMPT = 'INCREASE_LOGIN_ATTEMPT';
export const RESET_LOGIN_ATTEMPT = 'RESET_LOGIN_ATTEMPT';
export const CONFIRM_FB_EMAIL = 'CONFIRM_FB_EMAIL';
export const CLEAN_CONFIRM_FB_EMAIL = 'CLEAN_CONFIRM_FB_EMAIL';
export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_ERROR = 'GET_USER_INFO_ERROR';
export const WIPE_USER = 'WIPE_USER';
export const CONFIRM_SIGNUP_GOOGLE_PHONE = 'CONFIRM_SIGNUP_GOOGLE_PHONE'
export const TYPE_CONFIRM_OTP = 'TYPE_CONFIRM_OTP';
export const CHANGE_PHONE_STATUS = 'CHANGE_PHONE_STATUS';
export const GET_CAPTCHA_SUCCESS = 'GET_CAPTCHA_SUCCESS';
export const CHECK_CAPTCHA_SUCCESS = 'CHECK_CAPTCHA_SUCCESS';
export const CHECK_CAPTCHA_FAIL = 'CHECK_CAPTCHA_FAIL';


// PROFILE
export const GET_PROFILE_DETAIL_REQUEST = 'GET_PROFILE_DETAIL_REQUEST';
export const GET_PROFILE_DETAIL_SUCCESS = 'GET_PROFILE_DETAIL_SUCCESS';
export const GET_PROFILE_DETAIL_ERROR = 'GET_PROFILE_DETAIL_ERROR';
export const UPDATE_PROFILE_DETAIL = 'UPDATE_PROFILE_DETAIL';

// MEMBER CARD
export const GET_MEMBER_CARD_REQUEST = 'GET_MEMBER_CARD_REQUEST';
export const GET_MEMBER_CARD_SUCCESS = 'GET_MEMBER_CARD_SUCCESS';
export const GET_MEMBER_CARD_ERROR = 'GET_MEMBER_CARD_ERROR';
export const UPDATED_MEMBER_CARD = 'UPDATED_MEMBER_CARD';

// GIFT
export const GET_LIST_GIFT_REQUEST = 'GET_LIST_GIFT_REQUEST';
export const GET_LIST_GIFT_SUCCESS = 'GET_LIST_GIFT_SUCCESS';
export const GET_LIST_GIFT_ERROR = 'GET_LIST_GIFT_ERROR';

// CATEGORY
export const GET_PROVINCE_CATEGORY = 'GET_PROVINCE_CATEGORY';
export const GET_DISTRICT_CATEGORY = 'GET_DISTRICT_CATEGORY';
export const GET_WARD_CATEGORY = 'GET_WARD_CATEGORY';
export const GET_LIST_CATEGORY_REQUEST = 'GET_LIST_CATEGORY_REQUEST';
export const GET_LIST_CATEGORY_SUCCESS = 'GET_LIST_CATEGORY_SUCCESS';
export const GET_LIST_CATEGORY_ERROR = 'GET_LIST_CATEGORY_ERROR';
export const GET_CATEGORY_DETAIL_REQUEST = 'GET_CATEGORY_DETAIL_REQUEST';
export const GET_CATEGORY_DETAIL_SUCCESS = 'GET_CATEGORY_DETAIL_SUCCESS';
export const GET_CATEGORY_DETAIL_ERROR = 'GET_CATEGORY_DETAIL_ERROR';

// VIEW
export const SET_VIEW_HEIGHT = 'SET_VIEW_HEIGHT';

// PERMISSION
export const GET_LIST_PERMISSION_REQUEST = 'GET_LIST_PERMISSION_REQUEST';
export const GET_LIST_PERMISSION_SUCCESS = 'GET_LIST_PERMISSION_SUCCESS';
export const GET_LIST_PERMISSION_ERROR = 'GET_LIST_PERMISSION_ERROR';
export const GET_PERMISSION_DETAIL_REQUEST = 'GET_PERMISSION_DETAIL_REQUEST';
export const GET_PERMISSION_DETAIL_SUCCESS = 'GET_PERMISSION_DETAIL_SUCCESS';
export const GET_PERMISSION_DETAIL_ERROR = 'GET_PERMISSION_DETAIL_ERROR';

// ACCOUNT MANAGEMENT: USER
export const GET_LIST_USER_REQUEST = 'GET_LIST_USER_REQUEST';
export const GET_LIST_USER_SUCCESS = 'GET_LIST_USER_SUCCESS';
export const GET_LIST_USER_ERROR = 'GET_LIST_USER_ERROR';
export const GET_USER_DETAIL_REQUEST = 'GET_USER_DETAIL_REQUEST';
export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS';
export const GET_USER_DETAIL_ERROR = 'GET_USER_DETAIL_ERROR';
export const GET_LIST_USER_APP_REQUEST = 'GET_LIST_USER_APP_REQUEST';
export const GET_LIST_USER_APP_SUCCESS = 'GET_LIST_USER_APP_SUCCESS';
export const GET_LIST_USER_APP_ERROR = 'GET_LIST_USER_APP_ERROR';

// ACCOUNT MANAGEMENT: ROLE
export const GET_LIST_ROLE_PERMISSION_REQUEST =
  'GET_LIST_ROLE_PERMISSION_REQUEST';
export const GET_LIST_ROLE_PERMISSION_SUCCESS =
  'GET_LIST_ROLE_PERMISSION_SUCCESS';
export const GET_LIST_ROLE_PERMISSION_ERROR = 'GET_LIST_ROLE_PERMISSION_ERROR';
export const GET_LIST_ROLE_REQUEST = 'GET_LIST_ROLE_REQUEST';
export const GET_LIST_ROLE_SUCCESS = 'GET_LIST_ROLE_SUCCESS';
export const GET_LIST_ROLE_ERROR = 'GET_LIST_ROLE_ERROR';
export const GET_ROLE_DETAIL_REQUEST = 'GET_ROLE_DETAIL_REQUEST';
export const GET_ROLE_DETAIL_SUCCESS = 'GET_ROLE_DETAIL_SUCCESS';
export const GET_ROLE_DETAIL_ERROR = 'GET_ROLE_DETAIL_ERROR';

// ADMIN APPLICATION
export const GET_LIST_APPLICATION_REQUEST = 'GET_LIST_APPLICATION_REQUEST';
export const GET_LIST_APPLICATION_SUCCESS = 'GET_LIST_APPLICATION_SUCCESS';
export const GET_LIST_APPLICATION_ERROR = 'GET_LIST_APPLICATION_ERROR';
export const GET_APPLICATION_DETAIL_REQUEST = 'GET_APPLICATION_DETAIL_REQUEST';
export const GET_APPLICATION_DETAIL_SUCCESS = 'GET_APPLICATION_DETAIL_SUCCESS';
export const GET_APPLICATION_DETAIL_ERROR = 'GET_APPLICATION_DETAIL_ERROR';
export const GET_LIST_APPLICATION_USER_REQUEST =
  'GET_LIST_APPLICATION_USER_REQUEST';
export const GET_LIST_APPLICATION_USER_SUCCESS =
  'GET_LIST_APPLICATION_USER_SUCCESS';
export const GET_LIST_APPLICATION_USER_ERROR =
  'GET_LIST_APPLICATION_USER_ERROR';

// USER APPLICATION
export const GET_MANAGABLE_APPLICATION_REQUEST =
  'GET_MANAGABLE_APPLICATION_REQUEST';
export const GET_MANAGABLE_APPLICATION_SUCCESS =
  'GET_MANAGABLE_APPLICATION_SUCCESS';
export const GET_MANAGABLE_APPLICATION_ERROR =
  'GET_MANAGABLE_APPLICATION_ERROR';
export const SELECT_APP = 'SELECT_APP';
export const SET_EXCLUSIVE_NAV_ID = 'SET_EXCLUSIVE_NAV_ID';
export const SET_NAV_PARAM = 'SET_NAV_PARAM';

// SSO
export const DISPATCH_SUCESS = 'DISPATCH_SUCESS';
export const DISPATCH_ERROR = 'DISPATCH_ERROR';
export const TOGGLE_SSO_SUCCESS = 'TOGGLE_SSO_SUCCESS';
export const TOGGLE_SSO_ERROR = 'TOGGLE_SSO_ERROR';
export const SSO_AUTH_CODE_REQUEST = 'SSO_AUTH_CODE_REQUEST';
export const SSO_AUTH_CODE_SUCCESS = 'SSO_AUTH_CODE_SUCCESS';
export const SSO_AUTH_CODE_ERROR = 'SSO_AUTH_CODE_ERROR';


//OTP
export const OTP_REQUEST_START = 'OTP_REQUEST_START';
export const OTP_REQUEST_SUCCESS = 'OTP_REQUEST_SUCCESS';
export const OTP_REQUEST_FAIL='OTP_REQUEST_FAIL';
export const OTP_VERIFY_START='OTP_VERIFY_START';
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const OTP_VERIFY_FAIL='OTP_VERIFY_FAIL';
export const OTP_CHANGE_PHONE_NUMBER='OTP_CHANGE_PHONE_NUMBER';
export const OTP_RESET='OTP_RESET';
export const OTP_RESET_TIMEOUT='OTP_RESET_TIMEOUT';
