export const APPLICATION_TABLE_VIEW = 'APPLICATION_TABLE_VIEW';
export const APPLICATION_TABLE_UPDATE = 'APPLICATION_TABLE_UPDATE';
export const APPLICATION_TABLE_ADD_CLIENT = 'APPLICATION_TABLE_ADD_CLIENT';
export const APPLICATION_TABLE_REMOVE_CLIENT =
  'APPLICATION_TABLE_REMOVE_CLIENT';
