export const CATEGORY_TABLE_VIEW = 'CATEGORY_TABLE_VIEW';
export const CATEGORY_TABLE_UPDATE = 'CATEGORY_TABLE_UPDATE';
export const CATEGORY_TABLE_DUPLICATE = 'CATEGORY_TABLE_DUPLICATE';
export const CATEGORY_TABLE_DELETE = 'CATEGORY_TABLE_DELETE';
